CREATE TABLE USER (
  ID INT NOT NULL IDENTITY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE FRIEND (
  ID INT NOT NULL IDENTITY,
  USER_ID INT NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER
);