ALTER TABLE FRIEND ADD COLUMN SURNAME VARCHAR(100);

CREATE TRIGGER FRIEND_SURNAME_COPY BEFORE INSERT ON FRIEND
  REFERENCING NEW AS newrow FOR EACH ROW
  BEGIN ATOMIC
  IF newrow.surname IS NULL THEN
    SET newrow.surname = newrow.last_name;
  END IF;
  IF newrow.last_name IS NULL THEN
    SET newrow.last_name = newrow.surname;
  END IF;
END;

UPDATE FRIEND SET SURNAME = LAST_NAME;

ALTER TABLE FRIEND ALTER COLUMN SURNAME SET NOT NULL;